alias: 5_MQTT Dynamic POWERCALC
description: ""
triggers:
  - entity_id:
      - sensor.batteries_state_of_capacity #   senzor baterie 
      - sensor.power_meter_active_power    #   senzor import/export
      - sensor.powercalc_online
    trigger: state
actions:
  - data:
      topic: |
        {% if trigger.entity_id == 'sensor.batteries_state_of_capacity' %} #   senzor baterie 
          panouri/baterie
        {% elif trigger.entity_id == 'sensor.power_meter_active_power' %}  #   senzor import/export
          panouri/export
        {% elif trigger.entity_id == 'sensor.powercalc_online' %}
          online/{{ trigger.to_state.object_id }}
        {% else %}
          unknown
        {% endif %}
      payload: "{{ trigger.to_state.state }}"
    action: mqtt.publish
mode: single